print("22222")
print("they ask me how I do this-------------")
print("usher dances like------ ")
print("skyfall")
print("skyfall__2")
print("now merge is finished...")
print("before revert...")
print("counting revert")